@startuml
(*) --> "Ininialization"

if "Some Test" then
--> [true] "Some Activity"
--> "Another activitiy"
-right-> (*)
else
->[false] "Something else"
--> [Ending process] (*)
end if

(*) --> "check input"
if "input is verbose" then
--> [yes] "turn on verbosity"
--> "run command"
else
--> "run command"
endif
--> (*)
@enduml